return function(colors)
    return {
        ColorColumn          = { bg = colors.black2 },
        Conceal              = { fg = colors.grey1 },
        CurSearch            = { bg = colors.grey2 },
        Cursor               = { link = "Normal" },
        lCursor              = { link = "Cursor" },
        CursorIM             = { link = "Cursor" },
        CursorColumn         = { link = "Visual" },
        CursorLine           = { link = "Visual" },
        Directory            = { fg = colors.grey3, bold = true },
        DiffAdd              = { fg = colors.green },
        DiffChange           = { fg = colors.yellow },
        DiffDelete           = { fg = colors.red },
        DiffText             = { link = "Normal" },
        EndOfBuffer          = { fg = colors.grey3 },
        TermCursor           = { link = "Normal" },
        OkMsg                = { fg = colors.green },
        WarningMsg           = { fg = colors.red },
        ErrorMsg             = { link = "Error" },
        StderrMsg            = { link = "Error" },
        StdoutMsg            = { link = "Normal" },
        WinSeparator         = { fg = colors.black1, bg = colors.black1 },
        Folded               = { fg = colors.grey1 },
        FoldColumn           = { link = "Folded" },
        SignColumn           = { link = "Normal" },
        IncSearch            = { link = "Search" },
        Substitute           = { link = "Search" },
        LineNr               = { fg = colors.grey2 },
        LineNrAbove          = { link = "LineNr" },
        LineNrBelow          = { link = "LineNr" },
        CursorLineNr         = { fg = colors.grey3 },
        CursorLineFold       = { link = "FoldColumn" },
        CursorLineSign       = { link = "SignColumn" },
        MatchParen           = { fg = colors.orange1 },
        ModeMsg              = { link = "Normal" },
        MsgArea              = { link = "Normal" },
        MsgSeparator         = { fg = colors.grey3 },
        MoreMsg              = { fg = colors.grey3 },
        NonText              = { fg = colors.grey2 },
        Normal               = { fg = colors.white },
        NormalFloat          = { link = "Normal" },
        FloatBorder          = { fg = colors.white },
        FloatShadow          = { fg = colors.grey3 },
        FloatShadowThrough   = { link = "FloatShadow" },
        FloatTitle           = { link = "Title" },
        FloatFooter          = { link = "Title" },
        NormalNC             = { bg = colors.black1 },
        Pmenu                = { fg = colors.white },
        PmenuSel             = { bg = colors.black3 },
        PmenuKind            = { fg = colors.orange3 },
        PmenuKindSel         = { link = "PmenuSel" },
        PmenuExtra           = { fg = colors.grey2 },
        PmenuExtraSel        = { link = "PmenuKind" },
        PmenuSbar            = { fg = colors.grey3 },
        PmenuThumb           = { fg = colors.white },
        PmenuMatch           = { link = "CurSearch" },
        PmenuMatchSel        = { link = "PmenuSel" },
        PmenuBorder          = { link = "FloatBorder" },
        PmenuShadow          = { link = "FloatShadow" },
        PmenuShadowThrough   = { link = "FloatShadowThrough" },
        ComplMatchIns        = { link = "Search" },
        PreInsert            = { link = "Normal" },
        ComplHint            = { link = "Normal" },
        ComplHintMore        = { link = "Normal" },
        Question             = { link = "Normal" },
        QuickFixLine         = { link = "CursorLine" },
        Search               = { bg = colors.grey1 },
        -- SnippetTabstop       = {},
        -- SnippetTabstopActive = {},
        SpecialKey           = { link = "NonText" },
        SpellBad             = { sp = colors.red, undercurl = true },
        SpellCap             = { sp = colors.yellow, undercurl = true },
        SpellLocal           = { sp = colors.orange1, undercurl = true },
        SpellRare            = { sp = colors.grey2, undercurl = true },
        StatusLine           = { fg = colors.white, bg = colors.black1 },
        StatusLineNC         = { link = "StatusLine" },
        StatusLineTerm       = { link = "StatusLine" },
        StatusLineTermNC     = { link = "StatusLine" },
        -- TabLine              = {},
        -- TabLineFill          = {},
        -- TabLineSel           = {},
        Title                = { link = "Normal" },
        Visual               = { bg = colors.black2 },
        VisualNOS            = { link = "Visual" },
        Whitespace           = { bg = colors.black },
        WildMenu             = { link = "CursorLine" },
        WinBar               = { link = "StatusLine"},
        WinBarNC             = { link = "StatusLineNC" },
        -- Menu                 = {},
        -- ScrollBar            = {},
        -- Tooltip              = {},

        Comment              = { fg = colors.comment, italic = true },

        Constant             = { fg = colors.orange1 },
        String               = { fg = colors.grey2 },
        Character            = { link = "String" },
        Number               = { fg = colors.grey2 },
        Boolean              = { fg = colors.grey2 },
        Float                = { link = "Number" },

        Identifier           = { link = "Normal" },
        Function             = { fg = colors.orange2 },

        Statement            = { link = "Normal" },
        Conditional          = { link = "Normal" },
        Repeat               = { link = "Normal" },
        Label                = { link = "Normal" },
        Operator             = { link = "Normal" },
        Keyword              = { link = "Normal" },
        Exception            = { link = "Normal" },

        PreProc              = { link = "Normal" },
        Include              = { link = "PreProc" },
        Define               = { link = "PreProc" },
        Macro                = { link = "PreProc" },
        PreCondit            = { link = "PreProc" },

        Type                 = { fg = colors.grey3 },
        StorageClass         = { fg = colors.grey3 },
        Structure            = { fg = colors.grey3 },
        Typedef              = { fg = colors.grey3 },

        Special              = { fg = colors.grey3 },
        SpecialChar          = { link = "Special" },
        Tag                  = { link = "Special" },
        Delimiter            = { link = "Normal" },
        SpecialComment       = { link = "Special" },
        Debug                = { link = "Normal" },

        Underlined           = { underline = true },
        Ignore               = { fg = colors.black3 },
        Error                = { fg = colors.red },

        Added                = { link = "DiffAdd" },
        Changed              = { link = "DiffChange" },
        Removed              = { link = "DiffDelete" },
    }
end
