return function(colors)
    return {
        ["@variable"] = { link = "Normal" },
        ["@variable.builtin"] = { fg = colors.blue },
        ["@variable.parameter"] = { fg = colors.blue },
        ["@variable.parameter.builtin"] = { link = "@variable.parameter" },
        ["@variable.member"] = { link = "@variable" },

        ["@constant"] = { link = "Constant" },
        ["@constant.builtin"] = { link = "@constant" },
        ["@constant.macro"] = { link = "@constant" },

        ["@module"] = { fg = colors.orange3 },
        ["@module.builtin"] = { link = "@module" },

        ["@string"] = { link = "String" },
        ["@string.documentation"] = { link = "Comment" },
        ["@string.escape"] = { link = "SpecialChar" },
        ["@string.special"] = { link = "SpecialChar" },
        ["@string.special.symbol"] = { link = "@string.special" },
        ["@string.special.path"] = { link = "@sting.special" },
        ["@string.special.url"] = { link = "@string.special" },

        ["@character"] = { link = "Character" },
        ["@character.special"] = { link = "SpecialChar" },

        ["@boolean"] = { link = "Boolean" },
        ["@number"] = { link = "Number" },
        ["@number.float"] = { link = "Float" },

        ["@type"] = { fg = colors.orange3 },
        ["@type.builtin"] = { link = "Type" },
        ["@type.definition"] = { link = "Type" },

        ["@attribute"] = { link = "@variable.parameter" },
        ["@attribute.builtin"] = { link = "@attribute" },

        ["@property"] = { link = "Normal" },

        ["@function"] = { link = "Function" },
        ["@function.builtin"] = { link = "Normal" },
        ["@function.call"] = { link = "@function.builtin" },
        ["@function.macro"] = { link = "@function.builtin" },

        ["@function.method"] = { link = "@function" },
        ["@function.method.call"] = { link = "@function.call" },

        ["@constructor"] = { fg = colors.none, bg = colors.none },
        ["@operator"] = { link = "Normal" },

        ["@keyword"] = { link = "Keyword" },
        ["@keyword.coroutine"] = { link = "@keyword" },
        ["@keyword.function"] = { link = "@keyword" },
        ["@keyword.operator"] = { link = "@keyword" },
        ["@keyword.import"] = { link = "@type" },
        ["@keyword.type"] = { fg = colors.grey2 },
        ["@keyword.modifier"] = { link = "@keyword" },
        ["@keyword.repeat"] = { link = "@keyword" },
        ["@keyword.return"] = { fg = colors.orange1 },
        ["@keyword.debug"] = { link = "@keyword" },
        ["@keyword.exception"] = { link = "@keyword" },
        ["@keyword.conditional"] = { link = "@keyword" },
        ["@keyword.conditional.ternary"] = { link = "@keyword" },
        ["@keyword.directive"] = { link = "@comment" },
        ["@keyword.directive.define"] = { link = "@comment" },

        ["@punctuation.delimiter"] = { link = "Normal" },
        ["@punctuation.bracket"] = { link = "Normal" },
        ["@punctuation.special"] = { link = "Normal" },

        ["@comment"] = { link = "Comment" },
        ["@comment.documentation"] = { link = "@string.documentation" },

        ["@comment.error"] = { fg = colors.red, bold = true },
        ["@comment.warning"] = { fg = colors.yellow, bold = true },
        ["@comment.todo"] = { fg = colors.orange2, bold = true },
        ["@comment.note"] = { fg = colors.orange2, bold = true },

        ["@markup.strong"] = { bold = true },
        ["@markup.italic"] = { italic = true },
        ["@markup.strikethrough"] = { strikethrough = true },
        ["@markup.underline"] = { underline = true },

        ["@markup.heading.1"] = { fg = colors.orange3 },
        ["@markup.heading.2"] = { fg = colors.orange2 },
        ["@markup.heading.3"] = { fg = colors.orange1 },
        ["@markup.heading.4"] = { fg = colors.grey3 },
        ["@markup.heading.5"] = { fg = colors.grey2 },
        ["@markup.heading.6"] = { fg = colors.grey1 },

        ["@markup.quotes"] = { link = "@string" },
        ["@markup.math"] = { link = "@string" },

        ["@markup.link"] = { link = "@string.special.url" },
        ["@markup.link.label"] = { link = "@string.special.url" },
        ["@markup.link.url"] = { link = "@string.special.url" },

        ["@markup.raw"] = { fg = colors.grey2 },
        ["@markup.list"] = { link = "Normal" },

        ["@diff.plus"] = { link = "Added" },
        ["@diff.minus"] = { link = "Removed" },
        ["@diff.delta"] = { link = "Changed" },

        ["@lsp.type.boolean"] = { link = "@boolean" },
        ["@lsp.type.builtinType"] = { link = "@type.builtin" },
        ["@lsp.type.comment"] = { link = "@comment" },
        ["@lsp.type.decorator"] = { link = "@attribute" },
        ["@lsp.type.deriveHelper"] = { link = "@attribute" },
        ["@lsp.type.enum"] = { link = "@type" },
        ["@lsp.type.enumMember"] = { link = "@constant" },
        ["@lsp.type.interface"] = { link = "@type" },
        ["@lsp.type.formatSpecifier"] = { link = "Normal" },
        ["@lsp.type.generic"] = { link = "@variable" },
        ["@lsp.type.keyword"] = { link = "@keyword" },
        ["@lsp.type.namespace"] = { link = "@module" },
        ["@lsp.type.number"] = { link = "@number" },
        ["@lsp.type.operator"] = { link = "@operator" },
        ["@lsp.type.parameter"] = { link = "@variable.parameter" },
        ["@lsp.type.property"] = { link = "@property" },
        ["@lsp.type.selfKeyword"] = { link = "@variable.builtin" },
        ["@lsp.type.selfTypeKeyword"] = { link = "@variable.builtin" },
        ["@lsp.type.string"] = { link = "@string" },
        ["@lsp.type.typeAlias"] = { link = "@type.definition" },
        ["@lsp.type.unresolvedReference"] = { sp = colors.red, undercurl = true },
        ["@lsp.type.class"] = { link = "Normal" },
        ["@lsp.type.function"] = { link = "Normal" },

        ["@lsp.typemod.class.defaultLibrary"] = { link = "@type.builtin" },
        ["@lsp.typemod.enum.defaultLibrary"] = { link = "@type.builtin" },
        ["@lsp.typemod.enumMember.defaultLibrary"] = { link = "@constant.builtin" },
        ["@lsp.typemod.function.defaultLibrary"] = { link = "@function.builtin" },
        ["@lsp.typemod.keyword.async"] = { link = "@keyword.coroutine" },
        ["@lsp.typemod.keyword.injected"] = { link = "@keyword" },
        ["@lsp.typemod.macro.defaultLibrary"] = { link = "@type.builtin" },
        ["@lsp.typemod.method.defaultLibrary"] = { link = "@type.builtin" },
        ["@lsp.typemod.struct.defaultLibrary"] = { link = "@type.builtin" },
        ["@lsp.typemod.operator.injected"] = { link = "@operator" },
        ["@lsp.typemod.variable.defaultLibrary"] = { link = "@variable.builtin" },
        ["@lsp.typemod.variable.injected"] = { link = "@variable" },
        ["@lsp.typemod.variable.static"] = { link = "@constant" },

        ["@lsp.typemod.class.declaration"] = { fg = colors.orange3 },
        ["@lsp.typemod.function.declaration"] = { link = "@function" },
    }
end
